services:
  mysql-db:
    image: mysql:8.0
    container_name: qaforum_db_container
    restart: always
    environment:
      MYSQL_DATABASE: qaforum_db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - 3307:3306
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  app:
    build: .
    container_name: qaforum_app_container
    restart: always
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/qaforum_db?createDatabaseIfNotExist=true&useSSL=false&AllowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - mysql-db

volumes:
  db_data:
